name: bgmimobile
description: BGMI Mobile Free Stuff.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  better_player: ^0.0.81
  video_player: ^2.2.16
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  font_awesome_flutter: ^9.2.0
  shimmer_animation: ^2.1.0+1
  url_strategy: ^0.2.0
  google_fonts: ^2.2.0
  provider: ^6.0.2
  cloud_firestore: ^3.1.7
  url_launcher: ^6.0.18
  fluttertoast: ^8.0.8
  device_info_plus_web: ^2.1.0
  device_info_plus: ^3.2.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: block
      fonts:
        - asset: assets/font/block.otf
