// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVl8zSSTo7TxGK2XxwYV5nZQM3Sepcfe8',
    appId: '1:561391985110:web:dbe805718a4bba9ac0c477',
    messagingSenderId: '561391985110',
    projectId: 'bgmi-5d540',
    authDomain: 'bgmi-5d540.firebaseapp.com',
    storageBucket: 'bgmi-5d540.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-MwVq-wT_OKeTsgIp8iQWUTD-VUhJn0',
    appId: '1:561391985110:android:f30e138932015f96c0c477',
    messagingSenderId: '561391985110',
    projectId: 'bgmi-5d540',
    storageBucket: 'bgmi-5d540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZIUp2zTyyCiei3UFpOYaDIk9hG5wDuc',
    appId: '1:561391985110:ios:57c773c5cd9ed7aac0c477',
    messagingSenderId: '561391985110',
    projectId: 'bgmi-5d540',
    storageBucket: 'bgmi-5d540.appspot.com',
    iosClientId: '561391985110-6ehc6t9d69r8ock1ujbv91j7jk1g3sn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishing',
  );
}
